name = "atlas-blog"
main = "src/index.built.ts"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "atlas-blog"
database_id = "925d12da-afe9-4854-a407-da9c1d6e8e5d"

[[kv_namespaces]]
binding = "KV"
id = "b75e2501e7fd4edeb9052a55205e6ced"

[vars]
SITE_URL = "https://www.atlascorp.ae"

# Set ADMIN_PASSWORD as a secret via: wrangler secret put ADMIN_PASSWORD
# Set TOKEN_SECRET as a secret via: wrangler secret put TOKEN_SECRET

[[routes]]
pattern = "atlascorp.ae/admin"
zone_name = "atlascorp.ae"

[[routes]]
pattern = "atlascorp.ae/admin/*"
zone_name = "atlascorp.ae"

[[routes]]
pattern = "atlascorp.ae/api/*"
zone_name = "atlascorp.ae"

[[routes]]
pattern = "atlascorp.ae/blog/*"
zone_name = "atlascorp.ae"

[[routes]]
pattern = "www.atlascorp.ae/admin"
zone_name = "atlascorp.ae"

[[routes]]
pattern = "www.atlascorp.ae/admin/*"
zone_name = "atlascorp.ae"

[[routes]]
pattern = "www.atlascorp.ae/api/*"
zone_name = "atlascorp.ae"

[[routes]]
pattern = "www.atlascorp.ae/blog/*"
zone_name = "atlascorp.ae"

[dev]
port = 8787
local_protocol = "http"
